CC = clang
CXX = clang++
CXXFLAGS = -O3 -lm -std=c++11 -lpng -ffast-math
CFLAGS = -O3 -lm -std=c++11 -lpng -ffast-math
TARGETS = gaussian_blur

.PHONY: all
all: $(TARGETS)

.PHONY: clean
clean:
	rm -f $(TARGETS)
